name: Linux
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
#    - name: Install flatc
#      run: sudo apt-get install -y flatbuffers-compiler

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1.3.0
      with:
        version: master
        # version: 0.10.0
        # version: 0.11.0-dev.1987+a2c6ecd6d
    - run: zig build -Dbuild-sample run-sample
    - run: zig build test
    - run: zig build
 